### ISSUE TITLE
Uncaught exception: Error: Cannot find module 'clipboardy'

### ISSUE THREAD

**Issue by mscottford** [pluralsight/mob-timer#31]
Error message screenshot:
<img width="532" alt="Screen Shot 2019-04-11 at 2 33 14 PM" src="https://user-images.githubusercontent.com/21340/55982814-b89a0800-5c67-11e9-9005-43959c20ac1f.png">

macOS version info screenshot:
<img width="582" alt="Screen Shot 2019-04-11 at 2 38 19 PM" src="https://user-images.githubusercontent.com/21340/55982828-c0f24300-5c67-11e9-891b-df8341adc32a.png">

node and npm info: https://gist.github.com/mscottford/3922340252f9b79c2973ecb85e68b167

**Comment by jeremy-brooks** [comment]
Yep I'm getting this as well, I can see that the last few commits were to do with the clip board.

I tried rolling back to a few earlier commit points but no joy.

**Comment by jeremy-brooks** [comment]
Ok I rolled back to the commit hash `eb543b4935356948a198624ddada330927ae6e41` and it builds and runs ok from there.

**Comment by allan-stewart** [comment]
Thank you for discovering this @mscottford and @jeremy-brooks !

The problem was that the new `clipboardy` module was defined as a `devDependency` instead of a `dependency`. I should have caught this when the new feature was being developed, but I only ran it via `npm start` in a development mode and didn't remember to do a final build. Sorry about that.

This should be fixed now in 4ef1be8f

I hope you're enjoying the timer, and thanks again!
