### ISSUE TITLE
Ability to pause/deactivate a mobber

### ISSUE THREAD

**Issue by joejag** [pluralsight/mob-timer#6]
Hi,

There is currently an ability to add and remove mobbers from the timer. Where I am the mobs have different compositions at different times of the day, and when a person is away on holiday.

It would be good if there was a way to disable a mobber, rather than just deleting them, this would save me from having to keep adding the same names each day.

Can you let me know if this is a worthwhile feature for you?

Thank you,
Joe.

**Comment by mattcbaker** [comment]
@joejag we've thrown this into the hopper for discussion - we'll let you know shortly!

**Comment by allan-stewart** [comment]
@joejag Our team discussed this idea and feel like it has some potential, but in the short term doesn't add a lot of value.

If we did add this feature to the current mob timer, it would likely be a checkbox or button added to the configuration screen. So to enable or disable the mobber, you'd need to open the configuration screen anyway; at that point it feels like typing a few names isn't very difficult (and removing is a single click anyway). Since most teams know each other pretty well, typing in a name is hopefully not too much of a burden.

It sounds like our team doesn't change quite as often as yours, but we do get our fair share of switching mobbers and we've found the existing setup to be adequate.


However, we have also been discussing some ideas for further improvements. For example, we're considering adding mobber images to get away from being text-only. That will require metadata (image paths or perhaps email addresses for Gravatars), and that metadata adds overhead to adding a recurring mobber.

So for now we have decided to defer this feature request, but expect that we'll revisit it again in the future.

**Comment by joejag** [comment]
Hi @allan-stewart, that makes sense. It's certainly not a deal breaker for us either.

The images idea is pretty good. If someone was uploading an image, the ability to "pause" would be more beneficial.

I was thinking you could auto-detect twitter handles and pull the images too.

**Comment by allan-stewart** [comment]
Hey @joejag, not sure if you've been watching our experimental branch, but we've been making some more changes.

As of just now, I've merged those changes to master, so the mob timer has a new look that includes images. We hope you like it.

The change also includes an ability to enable/disable a mobber, so I'm going to close this issue.

**Comment by joejag** [comment]
Hi @allan-stewart,

I've just checked the latest version. I'm loving the graphical improvements you've made. Plus the pausing mentioned in this issue.

Thanks!
